name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
           login-server: azurecontainerregistryibm.azurecr.io
           username: AzureContainerRegistryIBM
           password: zHD/JY2mNsurY1QCVQLktVDI5YdIQIYo
      - run: |
          docker build . -t azurecontainerregistryibm.azurecr.io/azurewebapptoaks:${{ github.sha }}
          docker push azurecontainerregistryibm.azurecr.io/azurewebapptoaks:${{ github.sha }}
